language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

script:
  # the following command line builds the project and runs the tests
  - ./gradlew bootJar test javadoc asciidoc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build/asciidoc/html5
  target-branch: gh-pages
  on:
    branch: master
    jdk: openjdk8
